

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_timer"() RETURNS TABLE("id" integer, "is_running" boolean, "start_time" timestamp with time zone, "duration_sec" integer, "remaining_sec" integer, "server_time" timestamp with time zone)
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    AS $$
BEGIN
  RETURN QUERY
  SELECT
    t.id,
    t.is_running,
    t.start_time,
    t.duration_sec,
    t.remaining_sec,
    now() AS server_time
  FROM timer t
  WHERE t.id = 1;
END;
$$;


ALTER FUNCTION "public"."get_timer"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_timer_with_server_time"() RETURNS TABLE("id" integer, "is_running" boolean, "start_time" timestamp with time zone, "duration_sec" integer, "paused_remaining_sec" integer, "server_time" timestamp with time zone)
    LANGUAGE "plpgsql"
    AS $$
declare
  paused_remaining integer;
begin
  return query
  select
    t.id,
    t.is_running,
    t.start_time,
    t.duration_sec,
    case
      when t.is_running and t.start_time is not null then
        greatest(t.duration_sec - floor(extract(epoch from (now() - t.start_time))), 0)
      else
        t.remaining_sec  -- สมมุติว่าเก็บเวลาที่เหลือเมื่อหยุดไว้ใน column นี้
    end as paused_remaining_sec,
    now() as server_time
  from timer t
  where t.id = 1;
end;
$$;


ALTER FUNCTION "public"."get_timer_with_server_time"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."pause_timer"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  UPDATE timer
  SET is_running = FALSE,
      remaining_sec = duration_sec - FLOOR(EXTRACT(EPOCH FROM (NOW() - start_time)))
  WHERE id = 1;
END;
$$;


ALTER FUNCTION "public"."pause_timer"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."reset_timer"("new_duration" integer) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  update timer
  set 
    is_running = true,
    start_time = now(),
    duration_sec = new_duration,
    remaining_sec = null;
end;
$$;


ALTER FUNCTION "public"."reset_timer"("new_duration" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."resume_timer"() RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  UPDATE timer
  SET is_running = TRUE,
      start_time = NOW(),
      duration_sec = remaining_sec
  WHERE id = 1;
END;
$$;


ALTER FUNCTION "public"."resume_timer"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "auto_refresh" boolean
);


ALTER TABLE "public"."user_settings" OWNER TO "postgres";


ALTER TABLE "public"."user_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."autorefresh_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "position" integer NOT NULL
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."categories_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."categories_id_seq" OWNED BY "public"."categories"."id";



CREATE TABLE IF NOT EXISTS "public"."fight" (
    "round" integer NOT NULL,
    "node" "text" NOT NULL,
    "house" "text" NOT NULL,
    "count" integer,
    "tower" boolean DEFAULT false,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."fight" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."game_state" (
    "id" integer DEFAULT 1 NOT NULL,
    "status" "text" DEFAULT 'idle'::"text" NOT NULL,
    "round" integer DEFAULT 1 NOT NULL,
    CONSTRAINT "single_row" CHECK (("id" = 1))
);


ALTER TABLE "public"."game_state" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."leaderboard" (
    "house" "text" NOT NULL,
    "score" integer,
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."leaderboard" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."map_refresh_trigger" (
    "id" integer NOT NULL,
    "triggered_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."map_refresh_trigger" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."moves" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "house" "text" NOT NULL,
    "node" integer NOT NULL,
    "round" integer NOT NULL,
    "count" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "boat" integer
);


ALTER TABLE "public"."moves" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."nodes" (
    "id" "text" NOT NULL,
    "top" "text",
    "left" "text",
    "value" "text",
    "selectedcar" "text",
    "tower" boolean,
    "ship" "text"[],
    "fight" "jsonb"[],
    "towerOwner" "text"
);


ALTER TABLE "public"."nodes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."phase_logs" (
    "id" bigint NOT NULL,
    "phase" "text" NOT NULL,
    "message" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "text" DEFAULT 'preparing'::"text"
);


ALTER TABLE "public"."phase_logs" OWNER TO "postgres";


ALTER TABLE "public"."phase_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."phase_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."phases" (
    "id" bigint NOT NULL,
    "current_phase" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "admin_message" "text"
);


ALTER TABLE "public"."phases" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."positions" (
    "team_id" "text" NOT NULL,
    "score" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."positions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."purchases" (
    "id" integer NOT NULL,
    "house" "text" NOT NULL,
    "round" integer NOT NULL,
    "type" "text" NOT NULL,
    "node" integer NOT NULL,
    "count" integer NOT NULL,
    "create_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."purchases" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."purchases_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."purchases_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."purchases_id_seq" OWNED BY "public"."purchases"."id";



CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" integer NOT NULL,
    "category_id" integer,
    "number" integer NOT NULL,
    "label" "text",
    "points" integer DEFAULT 100 NOT NULL,
    "canva_url" "text"
);


ALTER TABLE "public"."questions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."questions_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."questions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."questions_id_seq" OWNED BY "public"."questions"."id";



CREATE TABLE IF NOT EXISTS "public"."score_events" (
    "id" bigint NOT NULL,
    "team_id" "text",
    "category_id" integer,
    "question_id" integer,
    "delta" numeric(10,2) NOT NULL,
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."score_events" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."score_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."score_events_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."score_events_id_seq" OWNED BY "public"."score_events"."id";



CREATE TABLE IF NOT EXISTS "public"."ship" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "house" "text" NOT NULL,
    "round" integer NOT NULL,
    "node" integer NOT NULL,
    "boat" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."ship" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."snapshots" (
    "node" "text" NOT NULL,
    "phase" "text" NOT NULL,
    "round" integer NOT NULL,
    "value" integer,
    "selectedcar" "text",
    "tower" boolean DEFAULT false,
    "ship" "text"[] DEFAULT '{}'::"text"[],
    "fight" "jsonb"[] DEFAULT '{}'::"jsonb"[],
    "towerOwner" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."snapshots" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."special_houses" (
    "house" "text" NOT NULL
);


ALTER TABLE "public"."special_houses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."teams" (
    "id" "text" NOT NULL,
    "name" "text" NOT NULL,
    "color" "text" NOT NULL
);


ALTER TABLE "public"."teams" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."team_scores" AS
 SELECT "t"."id" AS "team_id",
    "t"."name",
    "t"."color",
    COALESCE("sum"("e"."delta"), (0)::numeric) AS "score"
   FROM ("public"."teams" "t"
     LEFT JOIN "public"."score_events" "e" ON (("e"."team_id" = "t"."id")))
  GROUP BY "t"."id", "t"."name", "t"."color";


ALTER TABLE "public"."team_scores" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."timer" (
    "id" integer NOT NULL,
    "is_running" boolean DEFAULT false,
    "start_time" timestamp with time zone,
    "duration_sec" integer,
    "paused_remaining_sec" integer
);


ALTER TABLE "public"."timer" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."timer_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."timer_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."timer_id_seq" OWNED BY "public"."timer"."id";



ALTER TABLE ONLY "public"."categories" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."categories_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."purchases" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."purchases_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."questions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."questions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."score_events" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."score_events_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."timer" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."timer_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "autorefresh_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fight"
    ADD CONSTRAINT "fight_pkey" PRIMARY KEY ("round", "node", "house");



ALTER TABLE ONLY "public"."game_state"
    ADD CONSTRAINT "game_state_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leaderboard"
    ADD CONSTRAINT "leaderboard_pkey" PRIMARY KEY ("house");



ALTER TABLE ONLY "public"."map_refresh_trigger"
    ADD CONSTRAINT "map_refresh_trigger_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."moves"
    ADD CONSTRAINT "moves_house_round_node_key" UNIQUE ("house", "round", "node");



ALTER TABLE ONLY "public"."moves"
    ADD CONSTRAINT "moves_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."nodes"
    ADD CONSTRAINT "nodes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."phase_logs"
    ADD CONSTRAINT "phase_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."phases"
    ADD CONSTRAINT "phases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."positions"
    ADD CONSTRAINT "positions_pkey" PRIMARY KEY ("team_id");



ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_house_round_type_node_key" UNIQUE ("house", "round", "type", "node");



ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."score_events"
    ADD CONSTRAINT "score_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ship"
    ADD CONSTRAINT "ship_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."snapshots"
    ADD CONSTRAINT "snapshots_pkey" PRIMARY KEY ("node", "round", "phase");



ALTER TABLE ONLY "public"."special_houses"
    ADD CONSTRAINT "special_houses_pkey" PRIMARY KEY ("house");



ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."timer"
    ADD CONSTRAINT "timer_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "set_updated_at" BEFORE UPDATE ON "public"."phases" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."positions"
    ADD CONSTRAINT "positions_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id");



ALTER TABLE ONLY "public"."score_events"
    ADD CONSTRAINT "score_events_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id");



ALTER TABLE ONLY "public"."score_events"
    ADD CONSTRAINT "score_events_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id");



ALTER TABLE ONLY "public"."score_events"
    ADD CONSTRAINT "score_events_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE CASCADE;



CREATE POLICY "Allow all to select timer" ON "public"."timer" FOR SELECT USING (true);



CREATE POLICY "Allow all to update timer" ON "public"."timer" FOR UPDATE USING (true);



ALTER TABLE "public"."leaderboard" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."timer" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_settings" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."map_refresh_trigger";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."phase_logs";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."score_events";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."teams";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT ALL ON FUNCTION "public"."get_timer"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_timer"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_timer"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_timer_with_server_time"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_timer_with_server_time"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_timer_with_server_time"() TO "service_role";



GRANT ALL ON FUNCTION "public"."pause_timer"() TO "anon";
GRANT ALL ON FUNCTION "public"."pause_timer"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."pause_timer"() TO "service_role";



GRANT ALL ON FUNCTION "public"."reset_timer"("new_duration" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."reset_timer"("new_duration" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."reset_timer"("new_duration" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."resume_timer"() TO "anon";
GRANT ALL ON FUNCTION "public"."resume_timer"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."resume_timer"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."user_settings" TO "anon";
GRANT ALL ON TABLE "public"."user_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."user_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."autorefresh_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."autorefresh_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."autorefresh_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fight" TO "anon";
GRANT ALL ON TABLE "public"."fight" TO "authenticated";
GRANT ALL ON TABLE "public"."fight" TO "service_role";



GRANT ALL ON TABLE "public"."game_state" TO "anon";
GRANT ALL ON TABLE "public"."game_state" TO "authenticated";
GRANT ALL ON TABLE "public"."game_state" TO "service_role";



GRANT ALL ON TABLE "public"."leaderboard" TO "anon";
GRANT ALL ON TABLE "public"."leaderboard" TO "authenticated";
GRANT ALL ON TABLE "public"."leaderboard" TO "service_role";



GRANT ALL ON TABLE "public"."map_refresh_trigger" TO "anon";
GRANT ALL ON TABLE "public"."map_refresh_trigger" TO "authenticated";
GRANT ALL ON TABLE "public"."map_refresh_trigger" TO "service_role";



GRANT ALL ON TABLE "public"."moves" TO "anon";
GRANT ALL ON TABLE "public"."moves" TO "authenticated";
GRANT ALL ON TABLE "public"."moves" TO "service_role";



GRANT ALL ON TABLE "public"."nodes" TO "anon";
GRANT ALL ON TABLE "public"."nodes" TO "authenticated";
GRANT ALL ON TABLE "public"."nodes" TO "service_role";



GRANT ALL ON TABLE "public"."phase_logs" TO "anon";
GRANT ALL ON TABLE "public"."phase_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."phase_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."phase_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."phase_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."phase_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."phases" TO "anon";
GRANT ALL ON TABLE "public"."phases" TO "authenticated";
GRANT ALL ON TABLE "public"."phases" TO "service_role";



GRANT ALL ON TABLE "public"."positions" TO "anon";
GRANT ALL ON TABLE "public"."positions" TO "authenticated";
GRANT ALL ON TABLE "public"."positions" TO "service_role";



GRANT ALL ON TABLE "public"."purchases" TO "anon";
GRANT ALL ON TABLE "public"."purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."purchases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."purchases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."purchases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."purchases_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."questions" TO "anon";
GRANT ALL ON TABLE "public"."questions" TO "authenticated";
GRANT ALL ON TABLE "public"."questions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."score_events" TO "anon";
GRANT ALL ON TABLE "public"."score_events" TO "authenticated";
GRANT ALL ON TABLE "public"."score_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."score_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."score_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."score_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ship" TO "anon";
GRANT ALL ON TABLE "public"."ship" TO "authenticated";
GRANT ALL ON TABLE "public"."ship" TO "service_role";



GRANT ALL ON TABLE "public"."snapshots" TO "anon";
GRANT ALL ON TABLE "public"."snapshots" TO "authenticated";
GRANT ALL ON TABLE "public"."snapshots" TO "service_role";



GRANT ALL ON TABLE "public"."special_houses" TO "anon";
GRANT ALL ON TABLE "public"."special_houses" TO "authenticated";
GRANT ALL ON TABLE "public"."special_houses" TO "service_role";



GRANT ALL ON TABLE "public"."teams" TO "anon";
GRANT ALL ON TABLE "public"."teams" TO "authenticated";
GRANT ALL ON TABLE "public"."teams" TO "service_role";



GRANT ALL ON TABLE "public"."team_scores" TO "anon";
GRANT ALL ON TABLE "public"."team_scores" TO "authenticated";
GRANT ALL ON TABLE "public"."team_scores" TO "service_role";



GRANT ALL ON TABLE "public"."timer" TO "anon";
GRANT ALL ON TABLE "public"."timer" TO "authenticated";
GRANT ALL ON TABLE "public"."timer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."timer_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."timer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."timer_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























